pub mod commands;
#[rustfmt::skip] // generated by scripts/update-mods.js
pub mod domain;
pub mod market;
pub mod persistence;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .invoke_handler(tauri::generate_handler![
            commands::load_syndicates,
            commands::start_in_app_login,
            commands::capture_market_jwt,
            commands::cancel_login,
            commands::logout,
            commands::update_standing,
            commands::publish_syndicate,
            commands::record_sale,
            commands::get_faction_mods,
            commands::get_all_mods
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
